# A generic, single-database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration files
# file_template = %%(year)d_%%(month)02d_%%(day)02d_%%(hour)02d%%(minute)02d-%%(rev)s_%%(slug)s

# sys.path path, aligned with current execution directory
prepend_sys_path = .

# timezone to use when rendering the date within the migration file as well as the filename.
# string_value is passed to dateutil.tz.gettz or pytz.timezone.
# timezone =

# limit the number of revisions returned by the head/heads/history commands
# max_version_num =

# version location specification; this defaults
# to alembic/versions.  When using multiple version
# directories, paths must be separated by spaces.
# version_locations = %(here)s/bar %(here)s/bat alembic/versions

# the advance-iterator technology used to select version files.
# Default is 'lineage'; options are 'tree' or 'lineage'.
# version_iterator_flow = lineage

# logging configuration section
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARNING
handlers = console
qualname =

[logger_sqlalchemy]
level = WARNING
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
