import inspect
import os
import sys
from datetime import date, datetime
from typing import Any, Dict, List, Union, get_args, get_origin
from uuid import UUID

# Adjust path so `app.*` (backend/app/) is importable regardless of cwd.
# generate_ts_types.py -> scripts -> backend (2 levels up), matching the app package's home.
sys.path.append(os.path.dirname(os.path.dirname(__file__)))

from app.schemas import schemas


def map_python_type_to_ts(py_type: Any) -> str:
    """Map python typings to TypeScript representations."""
    origin = get_origin(py_type)
    args = get_args(py_type)

    if origin is Union:
        # Handle Optional[X] which is Union[X, NoneType]
        non_none_types = [t for t in args if t is not type(None)]
        ts_types = [map_python_type_to_ts(t) for t in non_none_types]
        # Join types, adding null
        return " | ".join(ts_types) + " | null"

    if origin is list or origin is List:
        item_type = args[0] if args else Any
        return f"{map_python_type_to_ts(item_type)}[]"

    if origin is dict or origin is Dict:
        key_type = map_python_type_to_ts(args[0]) if args else "string"
        val_type = map_python_type_to_ts(args[1]) if len(args) > 1 else "any"
        return f"Record<{key_type}, {val_type}>"

    # Base types
    if py_type is str or py_type is UUID:
        return "string"
    if py_type is int or py_type is float:
        return "number"
    if py_type is bool:
        return "boolean"
    if py_type is datetime or py_type is date:
        return "string"
    if py_type is Any:
        return "any"

    # If it's a Pydantic Model
    if hasattr(py_type, "__relation__") or (inspect.isclass(py_type) and hasattr(py_type, "model_fields")):
        return py_type.__name__

    # Fallback default
    if hasattr(py_type, "__name__"):
        return py_type.__name__
    return "any"


def generate_typescript_interfaces() -> str:
    """Reflect schemas and generate clean, compile-safe TypeScript interfaces."""
    output = [
        "/* tslint:disable */",
        "/* eslint-disable */",
        "/**",
        " * This file was automatically generated by generate_ts_types.py.",
        " * Do not modify this file manually.",
        " */",
        "",
    ]

    # Dynamically extract all schemas declared in the schemas module
    schemas_to_export = []
    for _name, obj in inspect.getmembers(schemas):
        if inspect.isclass(obj) and hasattr(obj, "model_fields") and obj.__module__ == schemas.__name__:
            schemas_to_export.append(obj)

    # Sort schemas to ensure parent classes or general types are parsed cleanly
    schemas_to_export.sort(key=lambda c: c.__name__)

    for schema in schemas_to_export:
        output.append(f"export interface {schema.__name__} {{")
        for field_name, field_info in schema.model_fields.items():
            annotation = field_info.annotation
            ts_type = map_python_type_to_ts(annotation)
            
            # Handle optional fields
            is_optional = get_origin(annotation) is Union and type(None) in get_args(annotation)
            optional_suffix = "?" if is_optional else ""
            
            # Append JSDoc description if present
            if field_info.description:
                output.append(f"  /** {field_info.description} */")
            
            output.append(f"  {field_name}{optional_suffix}: {ts_type};")
        output.append("}")
        output.append("")

    return "\n".join(output)


if __name__ == "__main__":
    ts_code = generate_typescript_interfaces()
    
    # Target directory path in frontend
    frontend_types_dir = os.path.join(
        os.path.dirname(os.path.dirname(os.path.dirname(__file__))),
        "frontend",
        "types"
    )
    
    os.makedirs(frontend_types_dir, exist_ok=True)
    target_filepath = os.path.join(frontend_types_dir, "generated.d.ts")
    
    with open(target_filepath, "w", encoding="utf-8") as f:
        f.write(ts_code)
        
    print(f"Successfully generated TypeScript interfaces in: {target_filepath}")
