/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by generate_ts_types.py.
 * Do not modify this file manually.
 */

export interface AgentExecutionLog {
  node: string;
  message: string;
  timestamp: string;
}

export interface AgentRunBase {
  session_id: string;
  ticker: string;
}

export interface AgentRunDetailResponse {
  run_id: string;
  ticker: string;
  status: string;
  logs: AgentExecutionLog[];
  report?: InvestmentReportSchema | null;
  telemetry: Record<string, any>;
}

export interface AgentRunSchema {
  session_id: string;
  ticker: string;
  id: string;
  status: string;
  started_at: string;
  ended_at?: string | null;
  report?: InvestmentReportSchema | null;
}

export interface AlertCreate {
  symbol: string;
  /** Trigger Type: rsi_below, rsi_above, sentiment_drop, price_above, price_below */
  trigger_type: string;
  trigger_value: number;
}

export interface AlertSchema {
  symbol: string;
  /** Trigger Type: rsi_below, rsi_above, sentiment_drop, price_above, price_below */
  trigger_type: string;
  trigger_value: number;
  id: string;
  session_id: string;
  is_active: boolean;
  created_at: string;
}

export interface IndexResponse {
  symbol: string;
  form_type: string;
  status: string;
  chunks_indexed: number;
}

export interface InvestmentReportSchema {
  id: string;
  run_id: string;
  ticker: string;
  recommendation: string;
  confidence_score: number;
  content_markdown: string;
  created_at: string;
}

export interface NewsResponse {
  symbol: string;
  headline: string;
  summary: string;
  url: string;
  source: string;
  published_at: string;
}

export interface PivotDetails {
  pivot: number;
  r1: number;
  s1: number;
  r2: number;
  s2: number;
}

export interface PortfolioBase {
  session_id: string;
  name: string;
}

export interface PortfolioCreate {
  name: string;
}

export interface PortfolioHoldingBase {
  symbol: string;
  shares: number;
  average_buy_price: number;
}

export interface PortfolioHoldingCreate {
  symbol: string;
  shares: number;
  average_buy_price: number;
}

export interface PortfolioHoldingSchema {
  symbol: string;
  shares: number;
  average_buy_price: number;
  id: string;
  portfolio_id: string;
  last_updated: string;
}

export interface PortfolioHoldingUpdate {
  shares: number;
  average_buy_price: number;
}

export interface PortfolioSchema {
  session_id: string;
  name: string;
  id: string;
  created_at: string;
  holdings: PortfolioHoldingSchema[];
}

export interface PortfolioSummaryHolding {
  id: string;
  portfolio_id: string;
  symbol: string;
  shares: number;
  average_buy_price: number;
  current_price: number;
  total_value: number;
  total_cost: number;
  gain_loss: number;
  gain_loss_percentage: number;
  sector: string;
  beta: number;
  volatility: number;
  last_updated?: string | null;
}

export interface PortfolioSummaryResponse {
  portfolio_id: string;
  name: string;
  total_value: number;
  total_cost: number;
  gain_loss: number;
  gain_loss_percentage: number;
  weighted_beta: number;
  weighted_volatility: number;
  holdings: PortfolioSummaryHolding[];
  sector_weights: Record<string, number>;
}

export interface QueryResponse {
  symbol: string;
  query: string;
  matches: SearchChunkDetail[];
}

export interface QuoteResponse {
  symbol: string;
  price: number;
  change: number;
  percent_change: number;
  high: number;
  low: number;
  open: number;
  previous_close: number;
  source: string;
}

export interface ReportHistoryItem {
  run_id: string;
  ticker: string;
  status: string;
  recommendation: string;
  confidence_score: number;
  created_at: string;
}

export interface ResearchQueryRequest {
  /** Natural language stock research query (e.g. Should I buy NVDA?) */
  query: string;
}

export interface SearchChunkDetail {
  text: string;
  section: string;
  chunk_id: number;
  score: number;
}

export interface SentimentResponse {
  symbol: string;
  score: number;
  rating: string;
  summary: string;
  opportunities: string[];
  threats: string[];
  source: string;
}

export interface SignalDetail {
  score: number;
  signal: string;
}

export interface StockBase {
  /** Stock Ticker Symbol */
  symbol: string;
  /** Company Name */
  name: string;
  sector?: string | null;
  industry?: string | null;
}

export interface StockCreate {
  /** Stock Ticker Symbol */
  symbol: string;
  /** Company Name */
  name: string;
  sector?: string | null;
  industry?: string | null;
}

export interface StockPriceBase {
  symbol: string;
  date: string;
  open: number;
  high: number;
  low: number;
  close: number;
  volume: number;
}

export interface StockPriceCreate {
  symbol: string;
  date: string;
  open: number;
  high: number;
  low: number;
  close: number;
  volume: number;
}

export interface StockPriceSchema {
  symbol: string;
  date: string;
  open: number;
  high: number;
  low: number;
  close: number;
  volume: number;
  id: string;
}

export interface StockSchema {
  /** Stock Ticker Symbol */
  symbol: string;
  /** Company Name */
  name: string;
  sector?: string | null;
  industry?: string | null;
}

export interface TASignals {
  rsi: SignalDetail;
  macd: SignalDetail;
  trends: SignalDetail;
  bollinger: SignalDetail;
  volume: SignalDetail;
}

export interface TechnicalPostureResponse {
  symbol: string;
  close: number;
  score: number;
  rating: string;
  signals: TASignals;
  summary: string;
  pivots?: PivotDetails | null;
}

export interface WatchlistCreate {
  symbol: string;
}

export interface WatchlistSchema {
  id: string;
  session_id: string;
  symbol: string;
  created_at: string;
}
