import type { Metadata } from "next";
import { MarketingShell } from "../../components/marketing/MarketingShell";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "The terms you agree to when using Alpha Hive, including the investment disclaimer.",
};

const UPDATED = "25 August 2026";

export default function TermsPage() {
  return (
    <MarketingShell>
      <article className="max-w-2xl mx-auto px-6 py-16 chat-prose">
        <h1 className="text-2xl font-semibold tracking-tight mb-1">Terms of Service</h1>
        <p className="text-[13px] text-mutedText mb-8">Last updated: {UPDATED}</p>

        <h2>Not investment advice</h2>
        <p>
          <strong>
            Alpha Hive provides educational research and analysis only. It is not investment
            advice.
          </strong>{" "}
          We are not a SEBI-registered investment adviser, a research analyst, or a broker. Nothing
          the agents produce is a recommendation to buy, sell or hold any security. Markets carry
          risk, including the loss of your capital. Every decision you make is your own, and you
          should verify independently — ideally with a registered adviser — before acting.
        </p>

        <h2>Accuracy</h2>
        <p>
          Answers are generated by language models reading third-party market data. Both can be
          wrong, stale or incomplete. Prices, filings and news may lag the market. We make no
          warranty as to accuracy, completeness or timeliness, and we are not liable for losses
          arising from reliance on the output.
        </p>

        <h2>Your account</h2>
        <p>
          You are responsible for keeping your password secure and for activity under your account.
          Tell us promptly if you believe it has been compromised. You must be old enough to enter a
          contract in your jurisdiction.
        </p>

        <h2>Acceptable use</h2>
        <ul>
          <li>Do not attempt to break, overload, or circumvent rate limits and access controls.</li>
          <li>Do not scrape, resell, or redistribute the output as your own financial advice.</li>
          <li>Do not use the service for anything unlawful, including market manipulation.</li>
        </ul>
        <p>
          Usage limits apply per session to keep costs sustainable. We may suspend accounts that
          abuse the service.
        </p>

        <h2>Availability</h2>
        <p>
          The service is provided &quot;as is&quot;, without warranty of any kind. We may change,
          suspend or discontinue any part of it, and we do not guarantee uninterrupted availability.
        </p>

        <h2>Limitation of liability</h2>
        <p>
          To the maximum extent permitted by law, we are not liable for any indirect, incidental or
          consequential damages, or for any trading or investment losses, arising out of your use of
          Alpha Hive.
        </p>

        <h2>Changes</h2>
        <p>
          We may update these terms. Continued use after a change means you accept the revised
          terms.
        </p>
      </article>
    </MarketingShell>
  );
}
